### ISSUE TITLE
Correcciones

### ISSUE THREAD

**Issue by jrsg** [UniversidadCristobalColon/pw2-e1-manolo0407#1]
Borraste al parecer sin querer la sección `head` junto con sus etiquetas `meta` y `title`

https://github.com/UniversidadCristobalColon/pw2-e1-manolo0407/blob/54ec0073cb9e948833ee49e2be1f91576d8c89b6/pw2-e1.html#L2

**Comment by manolo0407** [comment]
Se subió en el commit anterior
